import * as z from "zod";

export const RENAMED_PUBLIC_ENV = {
  // CONVEX
  CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,

  // CLERK
  CLERK_FRONTEND_API_URL: process.env.NEXT_PUBLIC_CLERK_FRONTEND_API_URL,
  CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
};

export const PUBLIC_ENV_TYPES = {
  // CONVEX
  CONVEX_URL: z.url("NEXT_PUBLIC_CONVEX_URL > URL"),

  // CLERK
  CLERK_FRONTEND_API_URL: z.url("NEXT_PUBLIC_CLERK_FRONTEND_API_URL > URL"),
  CLERK_PUBLISHABLE_KEY: z.string("NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY > string"),
};

export const PRIVATE_ENV_TYPES = {
  // CONVEX
  CONVEX_DEPLOYMENT: z.string("CONVEX_DEPLOYMENT > string"),

  // CLERK
  CLERK_SECRET_KEY: z.string("CLERK_SECRET_KEY > string"),
};
